### ISSUE TITLE
"transition superseded" errors with ui-router

### ISSUE THREAD

**Issue by reynoldsalec** [mattlewis92/angular-bluebird-promises#11]
Note that if you don't handle "transition superseded" and related errors from ui-router in "onPossiblyUnhandledRejection", you'll get a few of these errors from ui-router.

Something like this will eliminate the errors:

```
$q.onPossiblyUnhandledRejection(function(exception) {
  if(exception.message.match(/transition (superseded|prevented|aborted|failed)/)) {
    return;
  }
});
```

See https://gist.github.com/metamatt/6ab462818114833b7ee1 for other folks seeing this issue with bluebird and ui-router. Not sure if this is something angular-bluebird-promises should tackle.

**Comment by mattlewis92** [comment]
I agree that this isn't something this module should handle, but it does belong in the [readme](https://github.com/mattlewis92/angular-bluebird-promises/commit/4c735223807c66775420b668da8b551d88b43488).

Thanks for pointing it out! :smile:

**Comment by kamlekar** [comment]
@mattlewis92  so are we supposed to handle this as demonstrated by @reynoldsalec ?

**Comment by mattlewis92** [comment]
If you upgrade to ui-router 0.3.2 it's actually been fixed there: https://github.com/angular-ui/ui-router/commit/66ab048

**Comment by jackalvarez** [comment]
@mattlewis92 Could you please tell me how to update to that version?

**Comment by mattlewis92** [comment]
It depends on your project and what package manager (bower, npm etc) you're using.
