### ISSUE TITLE
Unit Specs and forcing Digests [question]

### ISSUE THREAD

**Issue by nmccready** [mattlewis92/angular-bluebird-promises#15]
So when originally using $q in order for `.then` to be kicked I need to digest the angular scope. However when moving to this library my specs `.then` is never kicked. 

Also in looking at the code base I see no $digest or $apply's anywhere. Not sure if this is dangerous or not.

Regardless; how do I force my promises to kick `.then` in angular specs.

**Comment by nmccready** [comment]
Actually I see your specs and it is the same situation https://github.com/mattlewis92/angular-bluebird-promises/blob/master/test/angular-bluebird-promises.spec.js#L93 . Anyway I still am puzzled why my spec is failing when this module is enabled vs having it off.

**Comment by mattlewis92** [comment]
This library uses bluebirds scheduler to trigger a digest as can be seen [here](https://github.com/mattlewis92/angular-bluebird-promises/blob/master/src/angular-bluebird-promises.js#L64). 

As it uses `$evalAsync` for performance reasons, you will manually need to trigger a `$rootScope.$digest()` in your tests for the promises to resolve.

**Comment by nmccready** [comment]
Ahh thank you; didn't see the $evalAsync. Still I am doing the $rootScope.$digest() and missing my `.then` callback.

**Comment by nmccready** [comment]
I may have to mock this up; but one more hint is that the spec I am testing is reliant on `$http` which in the spec is using `$httpBackend` so that might be a clue.

**Comment by mattlewis92** [comment]
What about if you call `$httpBackend.flush()`?

**Comment by nmccready** [comment]
Yeah doing that too.

**Comment by nmccready** [comment]
Let me get my digestor service.

**Comment by nmccready** [comment]
```js
app.service('digestor', function($rootScope, $timeout, $log, $httpBackend) {
  return {
    digest: function(scope, fn) {
      if (scope == null) {
        scope = $rootScope;
      }
      if (fn == null) {
        fn = function() {};
      }
      if (_.isFunction(scope)) {
        fn = scope;
        scope = $rootScope;
      }
      while ($timeout.hasPendingTasks()) {
        $timeout.flush();
      }
      if (fn != null) {
        fn();
      }
      if (!scope.$$phase) {
        scope.$digest();
      }
      if ($httpBackend.hasPendingRequests()) {
        return $httpBackend.flush();
      }
    }
  };
});

```

**Comment by nmccready** [comment]
Including provider extensison
```
app.service('digestor', function($rootScope, $timeout, $log, $httpBackend) {
  return {
    digest: function(scope, fn) {
      if (scope == null) {
        scope = $rootScope;
      }
      if (fn == null) {
        fn = function() {};
      }
      if (_.isFunction(scope)) {
        fn = scope;
        scope = $rootScope;
      }
      while ($timeout.hasPendingTasks()) {
        $timeout.flush();
      }
      if (fn != null) {
        fn();
      }
      if (!scope.$$phase) {
        scope.$digest();
      }
      if ($httpBackend.hasPendingRequests()) {
        return $httpBackend.flush();
      }
    }
  };
}).config(function($provide) {
  $provide.value('$log', console);
  $provide.decorator('$timeout', function($delegate, $browser) {
    $delegate.hasPendingTasks = function() {
      return $browser.deferredFns.length > 0;
    };
    return $delegate;
  });
  return $provide.decorator('$httpBackend', function($delegate) {
    $delegate.hasPendingRequests = function() {
      var pending;
      pending = false;
      try {
        $delegate.verifyNoOutstandingRequest();
      } catch (_error) {
        pending = true;
      }
      return pending;
    };
    return $delegate;
  });
});

```

**Comment by mattlewis92** [comment]
IIRC I had a similar problem before with bluebird promises not resolving in unit tests. Are you using mocha for testing? You could try just returning the promise at the end of your test

**Comment by nmccready** [comment]
Yes using karma with mocha test env with should, and chai. The problem is I am waiting on the specs done callback which is never getting hit. Which is supposed to be `.then () -> done()` . I just tried running the library via npm instead of bower since I thought maybe bluebird was not getting included correctly via main-bower-files; but I am still getting the same problem.

**Comment by mattlewis92** [comment]
If you return the promise to the unit test it won't require the done callback and it *might* solve your problem:
```
it('should be a test', () => {
  return $q.when();
});
```

**Comment by nmccready** [comment]
So mocha supports promises out of the box now? Since which version?

**Comment by nmccready** [comment]
Still though I am testing more than the promise itself.
```
promises[0].then ({data}) ->
            angular.equals(data,mockRoutes.geojsonPolys.response).should.equal true
            done()
```

**Comment by mattlewis92** [comment]
No idea how long they've supported promises, I think it's been for a while though.

Can you create the simplest possible example of it not working for you that I can run my end and I'll dig into it further tonight.

**Comment by nmccready** [comment]
Ok, I'll try to come up with something tonight. I'll probably just fork your lib and add spec to see if I can get it to fail. I might not get to it in a few days as I need to proceed without it right now.

**Comment by mattlewis92** [comment]
Did some digging on this tonight and it's definitely an issue with bluebird:
```
it('should be a test that never resolves', function(done) {
    var promise = new bluebird(function(resolve, reject) {
      resolve();
    });
    promise.then(function() {
      done();
    });
  });
```

will give:
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) $q should be a test that never resolves FAILED
	timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

but returning the promise to mocha works:
```
it('should be a test that never resolves', function() {
    var promise = new bluebird(function(resolve, reject) {
      console.log('it worked!');
      resolve();
    });
    return promise;
  });
```

I think this is just a difference between bluebird and angular that can't be worked around. A similar discussion went [on here](https://github.com/domenic/chai-as-promised/issues/68). 

Basically return any promises to mocha when using this library and put your assertions in the `.then` of the promise. Then you can also use libraries like this which would otherwise not have worked with `$q` promises before: https://github.com/domenic/chai-as-promised

**Comment by nmccready** [comment]
Thanks for looking; sorry I did not follow up.

**Comment by nmccready** [comment]
Wonder if this changes at all with 3.X bluebird?

**Comment by mattlewis92** [comment]
Nope, looks like the test still fails with 3.x
