### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by hccampos** [mattlewis92/angular-bluebird-promises#19]
This is a really cool idea and seems to work pretty nicely. However, when it comes to testing things become harder. Any plans for adding some mocks and maybe integrating with the existing angular ones?

**Comment by mattlewis92** [comment]
There was already some discussion on this [here](https://github.com/mattlewis92/angular-bluebird-promises/issues/15). 

As bluebird is not tied to angulars digest cycle you can't force a bluebird promise to resolve with a digest, however you can just return the promise to the test if using mocha like so:

```
it('should accept a promise', () => {
  return $q.when('value').then((result) => {
    expect(result).to.equal('value');
  });
});
```

This also allows you to use handy libraries like [this](https://github.com/domenic/chai-as-promised) which you previously couldn't have used with `$q`.
