### ISSUE TITLE
Bower install isn't sure about bluebird v3

### ISSUE THREAD

**Issue by JaKXz** [mattlewis92/angular-bluebird-promises#20]
Please see the screenshot below, but it seems that angular-bluebird-promises still depends on bluebird v2...

<img width="556" alt="screen shot 2015-11-19 at 1 37 15 pm" src="https://cloud.githubusercontent.com/assets/2642545/11280359/b5fea378-8ec3-11e5-8589-1d32edd94e79.png">

**Comment by mattlewis92** [comment]
I've just forgotten to set the allowed version in `bower.json`, it will work with bluebird 3

**Comment by mattlewis92** [comment]
Fixed: https://github.com/mattlewis92/angular-bluebird-promises/commit/5de1653da5ad0679e90c8721c575fc23e5bc5eed thanks for reporting!
