### ISSUE TITLE
Add main field into packageJSON

### ISSUE THREAD

**Issue by lucastschmidt** [mattlewis92/angular-bluebird-promises#22]
Hey man, since I am trying out electron, and you actually runs node code into chromium, there is no need to use browserify or those kind of technologies. 

But if you attempt to require this module, it fails due to main field missing. Can you please add it? Same as browser field used by browserify and others.

Thanks.

**Comment by mattlewis92** [comment]
Ah I never considered running this in electron, looks like there's no way for it to use the browser field which is a shame. I've changed it in 0.6.4 which should sort your problem :smile:
