### ISSUE TITLE
webpack require commonjs

### ISSUE THREAD

**Issue by beckend** [mattlewis92/angular-bluebird-promises#23]
Using webpack commonjs style:
```
aBP = require('angular-bluebird-promises');
```

```
angular.module('app', [ aBP ]);
```
Yields error, that being an object.

This however worked:
```
angular.module('app', [ aBP.default ]);
```
I guess this is an es6 thing...

**Comment by mattlewis92** [comment]
Ah it's a [babel issue](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default), it works fine if you're using babel as well, but using pure commonjs modules it fails. It should be fixed in 1.0.1. Thanks for reporting!
