### ISSUE TITLE
Stop requiring angular in your code

### ISSUE THREAD

**Issue by gotenxds** [mattlewis92/angular-bluebird-promises#25]
Since adding your library to my site I get this warning from angular: 

'WARNING: Tried to load angular more than once.'

This occurs because you require angular without checking if it is already exists.

**Comment by mattlewis92** [comment]
It looks more like an issue with your build system than a problem with this plugin, are you using browserify or webpack? And npm 2 or 3? Angular is only listed as a peer dependency which means this module should use the version of angular you have set in your package.json as a dependency.

**Comment by gotenxds** [comment]
Browserify + NPM 3.5


I do believe it does uses the angular version I use, but non the less it tries to require it although it already been initiated.

I use outer angular plugins none have this problem.

**Comment by mattlewis92** [comment]
Hmm it should resolve the angular version from the root of node_modules. Can you tell me the output of 
npm ls angular
From the root of your project

**Comment by gotenxds** [comment]
wit-client@0.1.0 C:\david\work\WIT\public
└── angular@1.4.9

**Comment by mattlewis92** [comment]
I think you just need to enable deduping with browserify, this should do the trick:
https://www.npmjs.com/package/browserify-resolutions

**Comment by mattlewis92** [comment]
Closing this as it can be solved with the plugin I mentioned previously.
