### ISSUE TITLE
Angular rejects promises with non-errors, is it possible to "fix" it without touching Bluebird's or Angular's source

### ISSUE THREAD

**Issue by KristjanTammekivi** [mattlewis92/angular-bluebird-promises#26]
I'm aware bluebird can be configured to not show warnings, but some warnings are really useful and I would like to keep those. Do You happen to know of a way to solve this? Thanks in advance!

**Comment by mattlewis92** [comment]
You just need to re-override the unhandledRejection callback like so:
https://github.com/mattlewis92/angular-bluebird-promises#unhandled-rejections

Hope this helps! 😄

**Comment by iddanh** [comment]
Your fix doesn't seem to be working, I'm still getting:
`Warning: a promise was rejected with a non-error: [object Object]`

**Comment by mattlewis92** [comment]
@iddanh a quick google reveals you can turn off all warnings in bluebird with:
```
Promise.config({
  warnings: false
});
```

I don't use bluebird or this module anymore so can't give you much more help I'm afraid 😞
