### ISSUE TITLE
$http.get() that failed generates bluebird type warning

### ISSUE THREAD

**Issue by Zergus** [mattlewis92/angular-bluebird-promises#28]
Hi,

I'm receiving type warning from bluebird when executing:
` get () { $http.get(config.api).then((response) => response; }).catch((reason) => reason; });}`.

Warning itself:
`Warning: a promise was rejected with a non-error: [object Object]`.

Stack trace leads to `angular.js:11908:66` where they got
`
(isSuccess(status) ? deferred.resolve : deferred.reject)({
          data: response,
          status: status,
          headers: headersGetter(headers),
          config: config,
          statusText: statusText
        });
`.

What I've found - this `[object Object]` is nothing but response object from `deffered.reject` with that data, status etc. Bluebird expected `Error` object instead of it.

Have any ideas? Problem for me - catch method is not executed in this case. The only applicable way for me to handle exception is transforming  method to:
`
    async get () {
        try {
            let response = await this.$http.get(config.api);
            return new UsersList(response.data);
        } catch (err) {
            return this.$log.error(err.message) && undefined;
        }
    }
`.

In this case exception will be catch and proceeded but warning message is still there.

Thanks.

**Comment by mattlewis92** [comment]
This is more of an issue with bluebird that this module which is a tiny wrapper around it, a quick google found:
```
Promise.config({
    warnings: false
});
```
which will disable all warnings
