### ISSUE TITLE
Unwanted digest cycles

### ISSUE THREAD

**Issue by jstans** [mattlewis92/angular-bluebird-promises#29]
I am using bluebird as my Promise library in the browser and have also included this library (along with angular), but I am getting $rootScope:inprog errors when Promise is being used directly.

I would have thought digests were only triggered when using $q but presumably it has extended the Promise object with this functionality? If so is there any recommended way to disable this?

**Comment by mattlewis92** [comment]
I think it's because of this: https://github.com/mattlewis92/angular-bluebird-promises/blob/master/src/angular-bluebird-promises.js#L71


To get the old behaviour I think you could do:
```
.run(($rootScope, Bluebird) => {
  Bluebird.setScheduler(cb => setTimeout(cb));
})
```

Although when a $q promise resolves it now won't trigger a digest.
