### ISSUE TITLE
A way to config to use $applyAsync instead

### ISSUE THREAD

**Issue by pocesar** [mattlewis92/angular-bluebird-promises#4]
Instead of having to manually override the Promise.setScheduler, offer a way to use $applyAsync. It's better for performance to hold off every promise resolutions to the next cycle, and one time only

**Comment by mattlewis92** [comment]
It already uses `$evalAsync` which will already do this. To [my understanding](http://www.bennadel.com/blog/2751-scope-applyasync-vs-scope-evalasync-in-angularjs-1-3.htm) the difference between `$applyAsync` and `$evalAsync` is the same as the difference between `$apply` and `$digest` and as `$evalAsync` is executed on the `$rootScope` there shouldn't be a difference.

**Comment by pocesar** [comment]
$applyAsync 'collects' everything that calls $applyAsync in the current $digest and schedules it to the next cycle.

**Comment by mattlewis92** [comment]
Yup, but $evalAsync does that as well.

**Comment by mattlewis92** [comment]
Closing as even $q uses $evalAsync for its next tick function: https://github.com/angular/angular.js/blob/master/src/ng/q.js#L221
