### ISSUE TITLE
Bluebird error logging is disabled

### ISSUE THREAD

**Issue by philippevk** [mattlewis92/angular-bluebird-promises#7]
Hi,
I noticed that unhandled rejected Promises aren't logged to the console. After looking at your code I tried commenting this line:
$qBluebird.onPossiblyUnhandledRejection(angular.noop)

And it seemed to solve the problem. So, my question is: Did you put this line because you dislike seeing the exceptions in the console or is it there a bug/problem that this line addresses?

Thanks!

**Comment by mattlewis92** [comment]
My reasoning for this was to mimic the default $q behaviour as closely as possible (which includes not logging unhandled rejections). As a rare edge case where it could break your app, if for example you used the ui-router it triggers the handler to run, and if you don't have a polyfill for console.log implemented for IE <= 9, it will break your production app simply by using this module.

As explained in the readme, you can and should add this behaviour back in yourself, see the readme for an example of how you can do this.

**Comment by philippevk** [comment]
Well, your reasonning makes a lot sense. I missed the logging part in the readme, thanks for pointing it out I'll do as you suggest. Cheers and good job writing this!
