### ISSUE TITLE
Bluebird Deferred Migration and Notify Question

### ISSUE THREAD

**Issue by simonsayscode** [mattlewis92/angular-bluebird-promises#8]
As per bluebird's Deferred Migration notes (https://github.com/petkaantonov/bluebird/blob/master/API.md#deferred-migration), shouldn't your $qBluebird defer code use something similar to:
```javascript
function defer() {
    var resolve, reject;
    var promise = new Promise(function() {
        resolve = arguments[0];
        reject = arguments[1];
    });
    return {
        resolve: resolve,
        reject: reject,
        promise: promise
    };
}
```
Also, in regards to progress - I see that you're supporting it since Angular has the notify on $q but I wonder since Bluebird has openly stated that they're deprecating and in the future not supporting progression (https://github.com/petkaantonov/bluebird/blob/master/API.md#progression-migration), how will you handle that? It seems like other angular $q/bluebird substitutions don't handle notify at all: https://github.com/angular/angular.js/issues/6697

**Comment by mattlewis92** [comment]
Using your defer implementation it doesn't allow you to use the notify callback. By not handling the notify callback this would break 3rd party libraries that require it, so leaving it out isn't really an option as this library is intended to be a complete shim for $q. I guess as a result this library will only be able to offer support for bluebird 2.x, I suppose I could offer an option to support 3.x when it's released with no support for notify / progress. However, when angular 2.0 is eventually released you will just be able to directly use bluebird with it and this library will become redundant.
