### ISSUE TITLE
Error handling conflicted with $exceptionHandler

### ISSUE THREAD

**Issue by lucastschmidt** [mattlewis92/angular-bluebird-promises#9]
Hey guys, if I override *$exceptionHandler* from angular and configure a *$q.onPossiblyUnhandledRejection*, I have exceptions that go thought both. 

Does that make any sense?

**Comment by mattlewis92** [comment]
I think it may be because of [this](http://stackoverflow.com/questions/23324942/angularjs-promises-rethrow-caught-exceptions). So if you `return $q.reject(new Error());` instead of `throw new Error();` from within the promise it shouldn't happen.

**Comment by lucastschmidt** [comment]
Thanks for the quick answer @mattlewis92 

I have an angular controller, that calls a method from a service:
```
Promise.try( (){
 // do something
}).catch( (error){
 throw AnotherError()
})
```
*Promise* that I am using is actually the *$q*. The error is being throw, and should be handled by *$exceptionHandler*, but is handled by both. I am using router-ui as well, but I dont think it should be any issues.

**Comment by lucastschmidt** [comment]
Thanks for the quick answer @mattlewis92 

My structure:
- router ui, going to a state, during the resolve, a security check is done.
```
      LoginService.isLoggedIn().then(function(isLoggedIn) {
        if (!isLoggedIn) {
          throw new NotLoggedInException();
        }
        return true;
      });
```
- so when I open a restricted page, and not logged in, an exception is thrown by router-ui during the resolve process
- $exceptionHandler handles it
- Bluebird follows it

**Comment by mattlewis92** [comment]
I don't see what's wrong here - as you're throwing an error it's picked up by the exceptionHandler, and as you're not explicitly adding a catch to the promise it's caught by the bluebird unhandled rejection handler. I don't think there's anything I can do to stop that, it's just an unfortunate side effect. You can stop the angular side of it by doing this instead:
```
LoginService.isLoggedIn().then(function(isLoggedIn) {
        if (!isLoggedIn) {
          return $q.reject(new NotLoggedInException());
        }
        return true;
});
```

Or add some logic in your bluebird handler to detect it

**Comment by lucastschmidt** [comment]
Sure @mattlewis92 , I already added a logic to handle multiple handles of the same exception.

Well, the issue was within router-ui architecture. Basically when a state is transitioned to another state, we have a promise. If it fails, it broadcasts an event with the error, but, at the same time it still rejects the promise itself. Which, I guess its the intended behaviour. 

(Since most people set up router-ui with configuration objects, you wont handle the rejection of the resolve promise directly, only by the broadcasted event, much more clean)

So, if a state change causes an error, it gets picked up by Bluebird as well, due to the reject promise.

Thanks @mattlewis92 for the help.
